import { Analytics } from '@vercel/analytics/react';

import type { Metadata } from 'next';

import { ubuntu } from './lib/fonts';

import '@/app/ui/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} bg-zinc-950 antialiased`}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
