import { SpeedInsights } from '@vercel/speed-insights/next';

import type { Metadata } from 'next';

import { ubuntu } from '@/app/lib/fonts';

import AuthProvider from '@/app/ui/providers/AuthProvider';

import '@/app/ui/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${ubuntu.className} bg-zinc-950 antialiased`}>
        <AuthProvider>{children}</AuthProvider>
        <SpeedInsights />
      </body>
    </html>
  );
}
